version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:latest
    container_name: elearning-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: elearning
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - elearning-network

  # Backend API server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: elearning-server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://admin:password@mongodb:27017/elearning?authSource=admin
      JWT_SECRET: your-jwt-secret-key
      PORT: 5001
    ports:
      - "5001:5001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mongodb
    networks:
      - elearning-network

  # Frontend client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: elearning-client
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    networks:
      - elearning-network

  # Redis for caching and session storage
  redis:
    image: redis:alpine
    container_name: elearning-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - elearning-network

  # MongoDB Express for database management
  mongo-express:
    image: mongo-express:latest
    container_name: elearning-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - elearning-network

volumes:
  mongodb-data:
  redis-data:

networks:
  elearning-network:
    driver: bridge