// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Tenant Types
export const GET_TENANTS = 'GET_TENANTS';
export const GET_TENANT = 'GET_TENANT';
export const TENANT_ERROR = 'TENANT_ERROR';
export const CREATE_TENANT = 'CREATE_TENANT';
export const UPDATE_TENANT = 'UPDATE_TENANT';
export const DELETE_TENANT = 'DELETE_TENANT';
export const SET_CURRENT_TENANT = 'SET_CURRENT_TENANT';
export const CLEAR_CURRENT_TENANT = 'CLEAR_CURRENT_TENANT';
export const CLEAR_TENANTS = 'CLEAR_TENANTS';

// Course Types
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE = 'GET_COURSE';
export const COURSE_ERROR = 'COURSE_ERROR';
export const CREATE_COURSE = 'CREATE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const SET_CURRENT_COURSE = 'SET_CURRENT_COURSE';
export const CLEAR_CURRENT_COURSE = 'CLEAR_CURRENT_COURSE';
export const CLEAR_COURSES = 'CLEAR_COURSES';
export const GET_COURSE_PROGRESS = 'GET_COURSE_PROGRESS';
export const UPDATE_COURSE_PROGRESS = 'UPDATE_COURSE_PROGRESS';

// Presentation Types
export const GET_PRESENTATIONS = 'GET_PRESENTATIONS';
export const GET_PRESENTATION = 'GET_PRESENTATION';
export const PRESENTATION_ERROR = 'PRESENTATION_ERROR';
export const CREATE_PRESENTATION = 'CREATE_PRESENTATION';
export const UPDATE_PRESENTATION = 'UPDATE_PRESENTATION';
export const DELETE_PRESENTATION = 'DELETE_PRESENTATION';
export const SET_CURRENT_PRESENTATION = 'SET_CURRENT_PRESENTATION';
export const CLEAR_CURRENT_PRESENTATION = 'CLEAR_CURRENT_PRESENTATION';
export const CLEAR_PRESENTATIONS = 'CLEAR_PRESENTATIONS';
export const GET_PRESENTATION_PROGRESS = 'GET_PRESENTATION_PROGRESS';
export const UPDATE_PRESENTATION_PROGRESS = 'UPDATE_PRESENTATION_PROGRESS';
export const PUBLISH_PRESENTATION = 'PUBLISH_PRESENTATION';
export const UNPUBLISH_PRESENTATION = 'UNPUBLISH_PRESENTATION';

// Quiz Types
export const GET_QUIZZES = 'GET_QUIZZES';
export const GET_QUIZ = 'GET_QUIZ';
export const QUIZ_ERROR = 'QUIZ_ERROR';
export const CREATE_QUIZ = 'CREATE_QUIZ';
export const UPDATE_QUIZ = 'UPDATE_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';
export const SET_CURRENT_QUIZ = 'SET_CURRENT_QUIZ';
export const CLEAR_CURRENT_QUIZ = 'CLEAR_CURRENT_QUIZ';
export const CLEAR_QUIZZES = 'CLEAR_QUIZZES';
export const GET_QUIZ_PROGRESS = 'GET_QUIZ_PROGRESS';
export const UPDATE_QUIZ_PROGRESS = 'UPDATE_QUIZ_PROGRESS';
export const PUBLISH_QUIZ = 'PUBLISH_QUIZ';
export const UNPUBLISH_QUIZ = 'UNPUBLISH_QUIZ';
export const ATTEMPT_QUIZ = 'ATTEMPT_QUIZ';
export const SUBMIT_QUIZ = 'SUBMIT_QUIZ';
export const GET_QUIZ_RESULTS = 'GET_QUIZ_RESULTS';

// Screenshot Types
export const GET_SCREENSHOTS = 'GET_SCREENSHOTS';
export const GET_SCREENSHOT = 'GET_SCREENSHOT';
export const SCREENSHOT_ERROR = 'SCREENSHOT_ERROR';
export const CREATE_SCREENSHOT = 'CREATE_SCREENSHOT';
export const UPDATE_SCREENSHOT = 'UPDATE_SCREENSHOT';
export const DELETE_SCREENSHOT = 'DELETE_SCREENSHOT';
export const SET_CURRENT_SCREENSHOT = 'SET_CURRENT_SCREENSHOT';
export const CLEAR_CURRENT_SCREENSHOT = 'CLEAR_CURRENT_SCREENSHOT';
export const CLEAR_SCREENSHOTS = 'CLEAR_SCREENSHOTS';
export const UPDATE_SCREENSHOT_ANNOTATIONS = 'UPDATE_SCREENSHOT_ANNOTATIONS';
export const MAKE_SCREENSHOT_PUBLIC = 'MAKE_SCREENSHOT_PUBLIC';
export const MAKE_SCREENSHOT_PRIVATE = 'MAKE_SCREENSHOT_PRIVATE';
export const DOWNLOAD_SCREENSHOT = 'DOWNLOAD_SCREENSHOT';
export const GET_SCREENSHOT_TAGS = 'GET_SCREENSHOT_TAGS';

// Tutorial Types
export const GET_TUTORIALS = 'GET_TUTORIALS';
export const GET_TUTORIAL = 'GET_TUTORIAL';
export const TUTORIAL_ERROR = 'TUTORIAL_ERROR';
export const CREATE_TUTORIAL = 'CREATE_TUTORIAL';
export const UPDATE_TUTORIAL = 'UPDATE_TUTORIAL';
export const DELETE_TUTORIAL = 'DELETE_TUTORIAL';
export const SET_CURRENT_TUTORIAL = 'SET_CURRENT_TUTORIAL';
export const CLEAR_CURRENT_TUTORIAL = 'CLEAR_CURRENT_TUTORIAL';
export const CLEAR_TUTORIALS = 'CLEAR_TUTORIALS';
export const GET_TUTORIAL_PROGRESS = 'GET_TUTORIAL_PROGRESS';
export const UPDATE_TUTORIAL_PROGRESS = 'UPDATE_TUTORIAL_PROGRESS';
export const PUBLISH_TUTORIAL = 'PUBLISH_TUTORIAL';
export const UNPUBLISH_TUTORIAL = 'UNPUBLISH_TUTORIAL';

// Analytics Types
export const GET_TENANT_ANALYTICS = 'GET_TENANT_ANALYTICS';
export const GET_USER_ANALYTICS = 'GET_USER_ANALYTICS';
export const GET_COURSE_ANALYTICS = 'GET_COURSE_ANALYTICS';
export const GET_PRESENTATION_ANALYTICS = 'GET_PRESENTATION_ANALYTICS';
export const GET_QUIZ_ANALYTICS = 'GET_QUIZ_ANALYTICS';
export const GET_SCREENSHOT_ANALYTICS = 'GET_SCREENSHOT_ANALYTICS';
export const GET_TUTORIAL_ANALYTICS = 'GET_TUTORIAL_ANALYTICS';
export const LOG_ACTIVITY = 'LOG_ACTIVITY';
export const ANALYTICS_ERROR = 'ANALYTICS_ERROR';

// Profile Types
export const GET_PROFILES = 'GET_PROFILES';
export const GET_RECOMMENDED_PROFILES = 'GET_RECOMMENDED_PROFILES';

// Share Types
export const GET_SHARES = 'GET_SHARES';
export const GET_SHARE = 'GET_SHARE';
export const SHARE_ERROR = 'SHARE_ERROR';
export const CREATE_SHARE = 'CREATE_SHARE';
export const UPDATE_SHARE = 'UPDATE_SHARE';
export const DELETE_SHARE = 'DELETE_SHARE';
export const TOGGLE_SHARE_STATUS = 'TOGGLE_SHARE_STATUS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_REPLY = 'ADD_REPLY';
export const RECORD_DOWNLOAD = 'RECORD_DOWNLOAD';
export const CLEAR_SHARE = 'CLEAR_SHARE';

// Collaboration Types
export const GET_COLLABORATIONS = 'GET_COLLABORATIONS';
export const GET_COLLABORATION = 'GET_COLLABORATION';
export const COLLABORATION_ERROR = 'COLLABORATION_ERROR';
export const CREATE_COLLABORATION = 'CREATE_COLLABORATION';
export const UPDATE_COLLABORATION = 'UPDATE_COLLABORATION';
export const DELETE_COLLABORATION = 'DELETE_COLLABORATION';
export const ADD_MEMBER = 'ADD_MEMBER';
export const ACCEPT_INVITATION = 'ACCEPT_INVITATION';
export const DECLINE_INVITATION = 'DECLINE_INVITATION';
export const REMOVE_MEMBER = 'REMOVE_MEMBER';
export const ADD_COMMENT_COLLAB = 'ADD_COMMENT_COLLAB';
export const ADD_REPLY_COLLAB = 'ADD_REPLY_COLLAB';
export const RESOLVE_COMMENT = 'RESOLVE_COMMENT';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CREATE_VERSION = 'CREATE_VERSION';
export const CLEAR_COLLABORATION = 'CLEAR_COLLABORATION';